//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesStore.Database
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class VideoGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoGame()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int VideoGameID { get; set; }
        public string VideoGameName { get; set; }
        public double VideoGamePrice { get; set; }
        public int VideoGameCategory { get; set; }
        public double VideoGameDiscount { get; set; }
        public int VideoGameDeveloper { get; set; }
        public string VideoGameDescription { get; set; }
        public string VideoGameImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Developer Developer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        public double VideoGameCostWithDiscount
        {
            get
            {
                return VideoGamePrice - (VideoGamePrice * (VideoGameDiscount / 100));
            }
        }
        
        public string VideoGameImagePath
        {
            get
            {
                string path = Environment.CurrentDirectory + @"\..\..\Resources" + VideoGameImage + ".png";

                if (File.Exists(path))
                    return path;
                else
                    return Environment.CurrentDirectory + @"\..\..\Resources\smileFace.png";
            }   
        }
        
}
}
